### ISSUE TITLE
推荐增加几个

### ISSUE THREAD

**Issue by hss01248** [guxiaonian/MobileInfo#4]
获取是否有刘海屏
获取外网ip： http://ip.taobao.com/service/getIpInfo2.php?ip=myip   ua要传pc的。
相机的各个摄像头的参数

**Comment by guxiaonian** [comment]
@hss01248  如果要获取网络相关的话 可以参考我这个项目 https://github.com/guxiaonian/HttpInfo
我之后将网络项目的readme合并过来  摄像头的各个参数有点繁杂 我这边看一下怎么规整  刘海屏和手机真实内部存储已经在排期了 这些得需要进行测试才可以 感谢您的建议

**Comment by iBotasky** [comment]
联系人信息也推荐获取一下

**Comment by hss01248** [comment]
> 联系人信息也推荐获取一下

联系人的功能有点重了

**Comment by chanchaw** [comment]
非常棒的案例，赞一个
