### ISSUE TITLE
获取cpu信息的时候  cpuTemp怎么是4368℃ ,什么单位?

### ISSUE THREAD

**Issue by zhang6jian** [guxiaonian/MobileInfo#9]

**Comment by guxiaonian** [comment]
我这边数据处理的问题，稍后我更新一版，现在是五位数以上会/1000来记摄氏温度

**Comment by zhang6jian** [comment]
> 我这边数据处理的问题，后来我更新一版，现在是五位数以上会/ 1000来记摄氏温度

嗯嗯  辛苦了  还有那个net字段里面能加下文档说明吗

**Comment by guxiaonian** [comment]
@zhang6jian  好的 我这边会有一个大版本的更新，加入了很多证书相关的硬件信息，近期会更新的，感谢您啦

**Comment by zhang6jian** [comment]
> @ zhang6jian 好的我这边会有一个大版本的更新，加入了很多证书相关的硬件信息，近期会更新的，感谢您啦

辛苦了 ,感谢
